name: generate snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
  
      - uses: Platane/snk@v3
        with:
          github_user_name: yifengcao3
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark

    
      - name: List generated files
        run: |
          pwd
          ls -alh
          ls -alh dist


      - name: Publish to output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: ./dist
          force_orphan: true
