name: generate snake

on:
  schedule:
    - cron: "0 0 * * *"   # 每天 00:00 UTC
  workflow_dispatch:

# 关键：给 GITHUB_TOKEN 写权限
permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: yifengcao3   # ← 你的用户名
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
