name: generate snake

on:
  schedule:
    - cron: "0 0 * * *"   # 每天 00:00 UTC 运行
  workflow_dispatch:

# 给内置 GITHUB_TOKEN 写权限，允许 push
permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      # 生成 SVG 到 dist/
      - uses: Platane/snk@v3
        with:
          github_user_name: yifengcao3          # ← 改成你的用户名
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark

      # 列出生成的文件，便于排错
      - name: List generated files
        run: |
          pwd
          ls -alh
          ls -alh dist

      # 强制把 dist/ 发布到 output 分支（不存在就创建）
      - name: Publish to output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: ./dist
          force_orphan: true
